import Head from "next/head";
import Image from "next/image";
import { useEffect, useState } from "react";
import Key from "../components/Key";
import Square from "../components/Square";
import styles from "../styles/Home.module.css";
import { l5words } from "../components/Words";

export default function Home() {
  const [chosenWord, setChosenWord] = useState(
    l5words[Number((Math.random() * l5words.length).toFixed(0))]
  );
  const [currentWord, setCurrentWord] = useState("");
  const [words, setWords] = useState([[], [], [], [], [], []]);
  const [round, setRound] = useState(0);
  const [enter, setEnter] = useState(false);
  const [state, setState] = useState(0);
  const [lettersUsed, setLettersUsed] = useState([]);

  const arr = [1, 1, 1, 1, 1];

  useEffect(() => {
    console.log(chosenWord);
  }, []);

  useEffect(() => {
    if (currentWord.length == 6 && currentWord[currentWord.length - 1] == "/") {
      let q = currentWord[0];
      let w = currentWord.substring(1, currentWord.length - 1);
      if ((q + w).toLowerCase() == chosenWord.toLowerCase()) {
        setState(3);
      }
      if (l5words.includes(q.toUpperCase() + w.toLowerCase())) {
        setRound(round + 1);
        if (round == 6) {
          setState(4);
        }
        setLettersUsed([...lettersUsed, ...currentWord.split("")]);
        setCurrentWord("");
        setEnter(true);
        console.log("right");
      } else {
        console.log("wrong");
        if (document.getElementsByClassName(styles.row_working)[0]) {
          document
            .getElementsByClassName(styles.row_working)[0]
            .classList.toggle(styles.row_anim);
        }
        setCurrentWord(currentWord.slice(0, currentWord.length - 1));
      }
    }
    let w = [...words];
    w[round] = currentWord.split("");
    setWords(w);
  }, [currentWord]);

  return (
    <div className={styles.container}>
      <Head>
        <title>JPS Wordle</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className={styles.header}>JPs Wordle</header>

      <main className={styles.main}>
        <div className={styles.letters}>
          <div
            className={
              round == 0 && state != 3 && state != 4
                ? styles.row_working
                : styles.row
            }
          >
            {arr.map((el, index) => {
              return (
                <Square
                  letter={words[0][index]}
                  chosenWord={chosenWord}
                  num={index}
                  enter={enter}
                  setenter={setEnter}
                  key={index}
                />
              );
            })}
          </div>
          <div
            className={
              round == 1 && state != 3 && state != 4
                ? styles.row_working
                : styles.row
            }
          >
            {arr.map((el, index) => {
              return (
                <Square
                  letter={words[1][index]}
                  chosenWord={chosenWord}
                  num={index}
                  enter={enter}
                  setenter={setEnter}
                  key={index}
                />
              );
            })}
          </div>
          <div
            className={
              round == 2 && state != 3 && state != 4
                ? styles.row_working
                : styles.row
            }
          >
            {arr.map((el, index) => {
              return (
                <Square
                  letter={words[2][index]}
                  chosenWord={chosenWord}
                  num={index}
                  enter={enter}
                  setenter={setEnter}
                  key={index}
                />
              );
            })}
          </div>
          <div
            className={
              round == 3 && state != 3 && state != 4
                ? styles.row_working
                : styles.row
            }
          >
            {arr.map((el, index) => {
              return (
                <Square
                  letter={words[3][index]}
                  chosenWord={chosenWord}
                  num={index}
                  enter={enter}
                  setenter={setEnter}
                  key={index}
                />
              );
            })}
          </div>
          <div
            className={
              round == 4 && state != 3 && state != 4
                ? styles.row_working
                : styles.row
            }
          >
            {arr.map((el, index) => {
              return (
                <Square
                  letter={words[4][index]}
                  chosenWord={chosenWord}
                  num={index}
                  enter={enter}
                  setenter={setEnter}
                  key={index}
                />
              );
            })}
          </div>
          <div
            className={
              round == 5 && state != 3 && state != 4
                ? styles.row_working
                : styles.row
            }
          >
            {arr.map((el, index) => {
              return (
                <Square
                  letter={words[5][index]}
                  chosenWord={chosenWord}
                  num={index}
                  enter={enter}
                  setenter={setEnter}
                  key={index}
                />
              );
            })}
          </div>
        </div>
        {state != 3 && state != 4 && (
          <div className={styles.keyboard}>
            <div className={styles.row}>
              <Key
                letter={"Q"}
                word={currentWord}
                setWord={setCurrentWord}
                used={lettersUsed}
                enterPressed={enter}
                chosenWord={chosenWord}
              />
              <Key
                letter={"W"}
                word={currentWord}
                setWord={setCurrentWord}
                used={lettersUsed}
                enterPressed={enter}
                chosenWord={chosenWord}
              />
              <Key
                letter={"E"}
                word={currentWord}
                setWord={setCurrentWord}
                used={lettersUsed}
                enterPressed={enter}
                chosenWord={chosenWord}
              />
              <Key
                letter={"R"}
                word={currentWord}
                setWord={setCurrentWord}
                used={lettersUsed}
                enterPressed={enter}
                chosenWord={chosenWord}
              />
              <Key
                letter={"T"}
                word={currentWord}
                setWord={setCurrentWord}
                used={lettersUsed}
                enterPressed={enter}
                chosenWord={chosenWord}
              />
              <Key
                letter={"Y"}
                word={currentWord}
                setWord={setCurrentWord}
                used={lettersUsed}
                enterPressed={enter}
                chosenWord={chosenWord}
              />
              <Key
                letter={"U"}
                word={currentWord}
                setWord={setCurrentWord}
                used={lettersUsed}
                enterPressed={enter}
                chosenWord={chosenWord}
              />
              <Key
                letter={"I"}
                word={currentWord}
                setWord={setCurrentWord}
                used={lettersUsed}
                enterPressed={enter}
                chosenWord={chosenWord}
              />
              <Key
                letter={"O"}
                word={currentWord}
                setWord={setCurrentWord}
                used={lettersUsed}
                enterPressed={enter}
                chosenWord={chosenWord}
              />
              <Key
                letter={"P"}
                word={currentWord}
                setWord={setCurrentWord}
                used={lettersUsed}
                enterPressed={enter}
                chosenWord={chosenWord}
              />
            </div>
            <div className={styles.row}>
              <Key
                letter={"A"}
                word={currentWord}
                setWord={setCurrentWord}
                used={lettersUsed}
                enterPressed={enter}
                chosenWord={chosenWord}
              />
              <Key
                letter={"S"}
                word={currentWord}
                setWord={setCurrentWord}
                used={lettersUsed}
                enterPressed={enter}
                chosenWord={chosenWord}
              />
              <Key
                letter={"D"}
                word={currentWord}
                setWord={setCurrentWord}
                used={lettersUsed}
                enterPressed={enter}
                chosenWord={chosenWord}
              />
              <Key
                letter={"F"}
                word={currentWord}
                setWord={setCurrentWord}
                used={lettersUsed}
                enterPressed={enter}
                chosenWord={chosenWord}
              />
              <Key
                letter={"G"}
                word={currentWord}
                setWord={setCurrentWord}
                used={lettersUsed}
                enterPressed={enter}
                chosenWord={chosenWord}
              />
              <Key
                letter={"H"}
                word={currentWord}
                setWord={setCurrentWord}
                used={lettersUsed}
                enterPressed={enter}
                chosenWord={chosenWord}
              />
              <Key
                letter={"J"}
                word={currentWord}
                setWord={setCurrentWord}
                used={lettersUsed}
                enterPressed={enter}
                chosenWord={chosenWord}
              />
              <Key
                letter={"K"}
                word={currentWord}
                setWord={setCurrentWord}
                used={lettersUsed}
                enterPressed={enter}
                chosenWord={chosenWord}
              />
              <Key
                letter={"L"}
                word={currentWord}
                setWord={setCurrentWord}
                used={lettersUsed}
                enterPressed={enter}
                chosenWord={chosenWord}
              />
            </div>
            <div className={styles.row}>
              <Key
                letter={"Enter"}
                big
                word={currentWord}
                setWord={setCurrentWord}
                enter={setEnter}
              />
              <Key
                letter={"Z"}
                word={currentWord}
                setWord={setCurrentWord}
                used={lettersUsed}
                enterPressed={enter}
                chosenWord={chosenWord}
              />
              <Key
                letter={"X"}
                word={currentWord}
                setWord={setCurrentWord}
                used={lettersUsed}
                enterPressed={enter}
                chosenWord={chosenWord}
              />
              <Key
                letter={"C"}
                word={currentWord}
                setWord={setCurrentWord}
                used={lettersUsed}
                enterPressed={enter}
                chosenWord={chosenWord}
              />
              <Key
                letter={"V"}
                word={currentWord}
                setWord={setCurrentWord}
                used={lettersUsed}
                enterPressed={enter}
                chosenWord={chosenWord}
              />
              <Key
                letter={"B"}
                word={currentWord}
                setWord={setCurrentWord}
                used={lettersUsed}
                enterPressed={enter}
                chosenWord={chosenWord}
              />
              <Key
                letter={"N"}
                word={currentWord}
                setWord={setCurrentWord}
                used={lettersUsed}
                enterPressed={enter}
                chosenWord={chosenWord}
              />
              <Key
                letter={"M"}
                word={currentWord}
                setWord={setCurrentWord}
                used={lettersUsed}
                enterPressed={enter}
                chosenWord={chosenWord}
              />
              <Key
                letter={"Del"}
                big
                word={currentWord}
                setWord={setCurrentWord}
              />
            </div>
          </div>
        )}
      </main>
    </div>
  );
}
